CREATE INDEX "appointments_start_time_idx" ON "appointments" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "appointments_staff_id_start_time_idx" ON "appointments" USING btree ("staff_id","start_time");--> statement-breakpoint
CREATE INDEX "appointments_customer_id_idx" ON "appointments" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "appointments_service_id_idx" ON "appointments" USING btree ("service_id");--> statement-breakpoint
CREATE INDEX "invoices_created_at_idx" ON "invoices" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "invoices_status_idx" ON "invoices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "payments_created_at_idx" ON "payments" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "service_consumables_service_id_idx" ON "service_consumables" USING btree ("service_id");--> statement-breakpoint
CREATE INDEX "service_consumables_product_id_idx" ON "service_consumables" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "services_category_id_idx" ON "services" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "products_category_id_idx" ON "products" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "order_item_consumables_order_item_id_idx" ON "order_item_consumables" USING btree ("order_item_id");--> statement-breakpoint
CREATE INDEX "order_item_consumables_product_id_idx" ON "order_item_consumables" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "service_order_items_order_id_idx" ON "service_order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "service_order_items_staff_id_idx" ON "service_order_items" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "service_order_items_service_id_idx" ON "service_order_items" USING btree ("service_id");--> statement-breakpoint
CREATE INDEX "service_order_products_order_id_idx" ON "service_order_products" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "service_order_products_order_item_id_idx" ON "service_order_products" USING btree ("order_item_id");--> statement-breakpoint
CREATE INDEX "service_order_products_product_id_idx" ON "service_order_products" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "service_orders_status_started_at_idx" ON "service_orders" USING btree ("status","started_at");--> statement-breakpoint
CREATE INDEX "service_orders_started_at_idx" ON "service_orders" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "service_orders_server_id_idx" ON "service_orders" USING btree ("server_id");--> statement-breakpoint
CREATE INDEX "service_orders_customer_id_idx" ON "service_orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "service_orders_appointment_id_idx" ON "service_orders" USING btree ("appointment_id");--> statement-breakpoint
CREATE INDEX "commission_logs_staff_id_idx" ON "commission_logs" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "commission_logs_invoice_id_idx" ON "commission_logs" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "commission_logs_service_order_item_id_idx" ON "commission_logs" USING btree ("service_order_item_id");--> statement-breakpoint
CREATE INDEX "expense_schedules_active_next_due_idx" ON "expense_schedules" USING btree ("is_active","next_due_date");--> statement-breakpoint
CREATE INDEX "expense_schedules_created_by_idx" ON "expense_schedules" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "expense_schedules_payee_staff_id_idx" ON "expense_schedules" USING btree ("payee_staff_id");--> statement-breakpoint
CREATE INDEX "expenses_date_idx" ON "expenses" USING btree ("date");--> statement-breakpoint
CREATE INDEX "expenses_status_idx" ON "expenses" USING btree ("status");--> statement-breakpoint
CREATE INDEX "expenses_logged_by_idx" ON "expenses" USING btree ("logged_by");--> statement-breakpoint
CREATE INDEX "expenses_schedule_id_idx" ON "expenses" USING btree ("schedule_id");--> statement-breakpoint
CREATE INDEX "expenses_payee_staff_id_idx" ON "expenses" USING btree ("payee_staff_id");--> statement-breakpoint
CREATE INDEX "product_usage_logs_product_id_idx" ON "product_usage_logs" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "product_usage_logs_order_id_idx" ON "product_usage_logs" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "product_usage_logs_staff_id_idx" ON "product_usage_logs" USING btree ("staff_id");--> statement-breakpoint
CREATE INDEX "stock_movements_product_id_created_at_idx" ON "stock_movements" USING btree ("product_id","created_at");--> statement-breakpoint
CREATE INDEX "stock_movements_created_at_idx" ON "stock_movements" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "stock_movements_performed_by_idx" ON "stock_movements" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "role_permissions_permission_id_idx" ON "role_permissions" USING btree ("permission_id");--> statement-breakpoint
CREATE INDEX "user_permissions_permission_id_idx" ON "user_permissions" USING btree ("permission_id");